version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "${FRONTEND_PORT:-8501}:8501" # Change if your binary listens on another port
    environment:
      - WS_SERVER_HOST=${WS_SERVER_HOST}
      - WS_SERVER_PORT=${WS_SERVER_PORT}
      - QUESTDB_CONFIG=${QUESTDB_CONFIG}
      - PRODUCT_IDS=${PRODUCT_IDS}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${WS_SERVER_PORT:-9001}:9001" # Change if your binary listens on another port
    environment:
      - WS_SERVER_HOST=${WS_SERVER_HOST}
      - WS_SERVER_PORT=${WS_SERVER_PORT}
      - ENDPOINT_ZMQ=${ENDPOINT_ZMQ}
      - QUESTDB_CONFIG=${QUESTDB_CONFIG}
      - PRODUCT_IDS=${PRODUCT_IDS}
      - RUST_LOG=${RUST_LOG:-info}

  ml:
    build:
      context: ./bc-ml-trading/bc-ml-trading
      dockerfile: Dockerfile
    container_name: ml
    ports:
      - "${ZMQ_PORT:-5555}:5555" # Change if your binary listens on another port
    environment:
      - ZMQ_HOST=${ZMQ_PORT}

  questdb:
    image: questdb/questdb:8.2.3
    ports:
      - "9000:9000"   # HTTP UI
      - "9009:9009"   # InfluxDB Line Protocol
      - "8812:8812"   # PostgreSQL Wire Protocol
      - "9003:9003"   # REST API & other internal services
    restart: unless-stopped
